[tool.poetry]
name = "parseval"
version = "0.1.0"
description = ""
authors = ["Imene KOLLI <53266529+imene-swaan@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.10"

# Crawler-specific dependencies
[tool.poetry.group.crawler]
optional = true

[tool.poetry.group.crawler.dependencies]
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
pyppeteer = "^2.0.0"


# Parser-specific dependencies
[tool.poetry.group.parser]
optional = true

[tool.poetry.group.parser.dependencies]
docling = "^2.1.0"
pymupdf = "^1.24.12"
pdfplumber = "^0.11.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
